### ISSUE TITLE
Commercial break in progress

### ISSUE THREAD

**Issue by SakhG** [odensc/ttv-ublock#1]
Basically same issue as [this thread](https://www.reddit.com/r/uBlockOrigin/comments/jkekvk/didnt_find_anything_on_the_subreddit_not_getting/)

No preroll but during a midroll this overlay is displayed, even on channels that claim to not have unscheduled midrolls (e.g. cohhcarnage)

**Comment by Osahashi** [comment]
had 4 midrolls a few minutes ago, seems twitch-videoad.js is not working anymore, every 15min I get two 15sec ads:

![Ad](https://user-images.githubusercontent.com/22057956/97778741-84ec3f00-1b79-11eb-982b-60ad0f4abba1.JPG)

**Comment by odensc** [comment]
The script does not block midrolls currently.

**Comment by Osahashi** [comment]
Your script works only for prerolls? Is there any working script at the moment? I completely lost the overview

**Comment by Osahashi** [comment]
Using your script makes this here:

![ads](https://user-images.githubusercontent.com/22057956/97800458-98f57680-1c35-11eb-99ff-4bf6bb446658.JPG)

**Comment by odensc** [comment]
I'll be implementing something that automatically resets the stream when this screen is detected.

**Comment by GyroMachinist** [comment]
I want to add onto this that they've punctured through the current ad-block system in the past hour or two. Now, we're getting spammed with annoying mid-roll ads where the "third party tool" warning message used to be.

**Comment by odensc** [comment]
Just updated for Twitch's latest patch. should remove prerolls again

**Comment by maddawg836** [comment]
wow, thanks for continuing the hard fight!

**Comment by EvaisaDev** [comment]
Did you already implement the stream reset thing? I wrote a userscript that does this but it uses the FFZ player reset system because I honestly do not quite understand how to reset the player myself.

**Comment by lewiskj** [comment]
this fix appears to no longer work; the "third party tool" message still appears. But thank you for fighting the good fight!

**Comment by odensc** [comment]
@lewiskj The Nov 2nd update does not block the midrolls. It just fixes the pre-rolls after Twitch patched it around 3:00 pm PST.

@EvaisaGiac I'm still working on it, trying to figure out how to reset the player without FFZ and without a full page reload.

**Comment by PepegaLight** [comment]
Worked fine, about 10 minutes ago I got a pre-roll ad after refreshing Twitch. I purged the cache and updated, just in case. Got a mid-roll ad.
![BJ6FUL4](https://user-images.githubusercontent.com/73866486/97947254-ff40dd00-1d8c-11eb-9f31-39f774e93bda.png)

Small update: No ad since I posted this so far, no empty mid-rolls either.

Update2: Yep, got a full mid-roll ad after 40 minutes.

**Comment by ZooBuZZ** [comment]
First I just want to say thank you for working on this.  Twitch is almost unwatchable these days with the crazy amount of ads.  The current version does seem to be blocking pre-roll ads for me, as well as ads that run on the top of the chat-box area.  So at least when an ad starts I can still see the stream in that small area.  But I am seeing the third party tool blocking error during mid-roll ads.  At least it is better than sitting through a toxic ad!  If there is any way I can help troubleshoot let me know!  (I watch a lot of twitch, but I am not an expert with ublock origin.)

**Comment by Mspy1** [comment]
I got a mid-roll ad, then I refreshed the page with the hopes of skipping that mid-roll ad that way, but that also didn't work.

**Comment by odensc** [comment]
Anyone getting the midroll "third-party tool" screen, please try this script: https://gist.githubusercontent.com/odensc/accbd80cc5c3b796c5ea484a385b742f/raw/9f84cde34abe4be95b562d87a2e1de392f3ce31e/pbp-test.js

Basically, when it detects an ad, it unmutes and overlays the mini picture-by-picture player on top of the main player. This will temporarily drop the stream quality to 360p (which the mini player is limited to) for like 20 seconds while the screen is up.

(some people don't seem to get the mini player during ads, in which case it wouldn't work I suppose)

If it gets favorable results I will probably add it to the main script.

Edit: one other quirk, it probably won't work in full screen

**Comment by maddawg836** [comment]
Just had first experience with new method which I do like. A slight problem with it is the audio gets very loud and volume is unchangeable during the overlay. After it switches back it goes back to normal.

**Comment by odensc** [comment]
Hm really? It should [copy over the volume](https://gist.github.com/odensc/accbd80cc5c3b796c5ea484a385b742f#file-pbp-test-js-L36). Will test that next time I get one.

I'll also see if I can figure out an elegant way to overlay the volume control.

**Comment by maddawg836** [comment]
Can confirm that only mute works and the volume does get changed, i think it maxes.

**Comment by EvaisaDev** [comment]
Someone else has been working on tackling the same issue, it also has (or had(?)) audio issues
https://github.com/Wilkolicious/twitchAdSkip
I am pretty sure this uses the FFZ reload just like my own though.

**Comment by TheOne320** [comment]
For me about an hour ago even the pre-roll ads started playing again.

**Comment by Wilkolicious** [comment]
> 
> 
> Someone else has been working on tackling the same issue, it also has (or had(?)) audio issues
> https://github.com/Wilkolicious/twitchAdSkip
> I am pretty sure this uses the FFZ reload just like my own though.

The only issue I'm aware of related to audio, is the slider just isn't in sync, i.e. cosmetic issue, i.e. low prio.  The volume is persisted through stream refreshes.

**Comment by odensc** [comment]
In my testing I haven't had this screen show up with the latest (Nov 5th 2:40PM PST) update. Either twitch hasn't yet updated this player_type to inject the anti-adblock ads, or I've just been lucky the last 30 mins (which is possible). Anyone else?

**Comment by Wilkolicious** [comment]
I'm mentally preparing myself to see the `twitchAdSkip` script completely not working soon, because no way would they be this generous.

**Comment by maddawg836** [comment]
I think there is a new recent problem with the temp script. I was unable to get past 480p streams and it was on auto (source didn't show up at all). I purged and refreshed but still didn't work. turned off ublock and source was back. I changed to older script and refreshed and source is back.

**Comment by odensc** [comment]
Yes twitch recently locked the previous fix to 480p (which is what that temp script was using). I updated the main script but not that one yet.

**Comment by maddawg836** [comment]
Main script is down to 360 now. twitch is really something else

**Comment by odensc** [comment]
Yep. World record speedrun for Twitch I think! Either remove the script or update it to the latest version which essentially does nothing until we find a new fix.

**Comment by Wilkolicious** [comment]
160p next men.  Prepare yourself for the eventual audio-only streams you filthy ad-blocking plebians!!11

**Comment by kapistelijaJami** [comment]
So how many player types are still left? And what are the next ideas when they run out?

**Comment by odensc** [comment]
@kapistelijaJami Precisely zero at the moment. If I find another, or an alternate solution, it'll probably wait 'til the weekend because Twitch is trigger-happy now.

**Comment by kapistelijaJami** [comment]
@odensc Yeah, I realized you changed it back to site. Tbh, the tampermonkey script that uses FFZ to refresh the player is usable right now. It goes like 5-10 times when ad comes, it's over in couple seconds, and then there's like half an hour break or something for that streamer. Still annoying, so hoping for a better solution, but holy shit twitch is going hard right now.

**Comment by EvaisaDev** [comment]
Current script gets stuck on preroll ads completely for me now.
[Edit]
Actually it got past the ad loop after 30 seconds or so.

**Comment by EvaisaDev** [comment]
You know what's funny to me, I know this helps in no way but in the cinema gamemode of the game garry's mod you don't get any twitch ads even though it uses chromium and runs directly through the twitch website afaik. Some kind of full screen steam which also shows the button when the stream includes adult content and you have to click the button to show the stream.
(I just noticed it by accident yesterday)

**Comment by Eco-23** [comment]
I have a solution but I had to write a new extension for it. It blocks all ads, pre-roll and commercial with full quality and doesn't involve editing the page or sending anything to the twitch server.

Simply edit the .m3u8 file live as it's received to strip out the stitched ads, each ad includes a refer link and an amazon link so it's simple to remove. You could also create an automatic blacklist to push the refer & amazon affiliate links straight to the block list.

**Comment by odensc** [comment]
@Eco-23 Does that not cause gaps in the stream where those ads would usually play?

**Comment by ZooBuZZ** [comment]
> I have a solution but I had to write a new extension for it. It blocks all ads, pre-roll and commercial with full quality and doesn't involve editing the page or sending anything to the twitch server.
> 
> Simply edit the .m3u8 file live as it's received to strip out the stitched ads, each ad includes a refer link and an amazon link so it's simple to remove. You could also create an automatic blacklist to push the refer & amazon affiliate links straight to the block list.

I don't know what some of this means, but am I misunderstanding, or is there a way a filter list could be made and shared?
