### ISSUE TITLE
Any plans to put the extension on the Chrome Web Store?

### ISSUE THREAD

**Issue by TheRealDannyyy** [odensc/ttv-ublock#10]
Would be much easier for people with less experience to get the extension on the [Chrome Web Store](https://chrome.google.com/webstore/category/extensions), with automatic updates and such. Are there any plans for this or is it perhaps already being denied by Google?

**Comment by jonyroda97** [comment]
It was waiting for approval as said in the README.
It is already available. Link in the README

**Comment by TheRealDannyyy** [comment]
Oh must be a recent addition, sorry for missing it. From the looks of it, it's outdated. 
My best guess is that the update is waiting for approval as well.

**Comment by jonyroda97** [comment]
No problem and you are right (chrome takes a lot of time to review submissions).
You can get the update and manually installing it here: https://github.com/odensc/ttv-ublock/issues/8#issuecomment-728633409

**Comment by TheRealDannyyy** [comment]
Got it. Thanks for the info!
