### ISSUE TITLE
Ads in pop out player

### ISSUE THREAD

**Issue by qwopsin** [odensc/ttv-ublock#14]
When you pop out the player, the player in the new window has ads.

I think the fix is updating the `matches` for the `content_scripts` in `manifest.json` so it includes `player.twitch.tv` as well.
(perhaps to `"*://*.twitch.tv/*"`)

Thank you for all the great work!

**Comment by PureFallen** [comment]
When supported by the device, a workaround could be to use the browsers inbuild PiP (Picture in Picture) Mode to popout the player. This also has the advantage, that you don't have to deal with the borders of a new window.

The bad news is that the Twitch Playeroverlay also overlays the PiP Button by most browsers, as well of the context menu option.
The good news is that you can also use a hotkey to achieve that. In case of Firefox that should be CTRL + SHIFT + ] or CTRL + SHIFT + }, both works.
Depending on Keyboardlayout that might look different, too. In case of a german keyboard layout, CTRL + SHIFT + 9 is the way to go.

**Comment by strong-code** [comment]
I tried these changes and it seems to work (win 10, firefox 83). Jumped around to a couple users where I was previously getting ad rolls in popout player and this successfully avoided them. Would appreciate if other users (particularly Chrome users) could help test and make sure it looks ok.

**Comment by nolifepleb** [comment]
> When you pop out the player, the player in the new window has ads.
> 
> I think the fix is updating the `matches` for the `content_scripts` in `manifest.json` so it includes `player.twitch.tv` as well.
> (perhaps to `"*://*.twitch.tv/*"`)
> 
> Thank you for all the great work!

This fixed it for me. Please update the extension with this change for people who use pop out player. 👍 Tested on Chrome.

**Comment by odensc** [comment]
Fixed by @strong-code's PR, 2.1.0 is out on Firefox and pending review on Chrome
