### ISSUE TITLE
No channel points

### ISSUE THREAD

**Issue by Edgeexe** [odensc/ttv-ublock#15]
Current version disable channel points gains, if there's no workaround this, can the extension be disabled in specific channels?

**Comment by RoyRiv3r** [comment]
Don't have this problem, channel points are working properly, make sure you did disable the tampermonkey script if you have it and nothing can interfere

**Comment by odensc** [comment]
Yeah this shouldn't interfere with channel points, and many people have confirmed as such. Make sure you don't have the UserScript or anything else conflicting installed.
