### ISSUE TITLE
Here is how another project blocked embedded ads

### ISSUE THREAD

**Issue by dusty-dusty** [odensc/ttv-ublock#22]
As TTV-ublock does not work anymore, here solution that another project I follow blocks ads. Hope this helps you fix the issue for browsers.

https://github.com/streamlink/streamlink/issues/3210

I have yet to see an ad using this

**Comment by Phistr90** [comment]
Also same purple screen with streamlink.

**Comment by TheKins** [comment]
I haven't seen purple screens with the latest Nightly build of Streamlink, though I did notice one stream that had a very brief flicker of what might have been one, for like one frame once a second for about a minute or so.

**Comment by dusty-dusty** [comment]
> Also same purple screen with streamlink.

If you download the nightly build you won't get the purple screen and use the no ads parameters. I watched soda today and at the end of his stream he played 10min of ads to farm people that went to bed. I did not get one ad. Also did not get ads after Tyler1 games when he plays them. 


> I haven't seen purple screens with the latest Nightly build of Streamlink, though I did notice one stream that had a very brief flicker of what might have been one, for like one frame once a second for about a minute or so.

You should make a report about that. I have not experienced it.

**Comment by odensc** [comment]
Looking at the code Streamlink uses the exact same method as this extension. So if you're not seeing any purple screen it's likely a fluke.
