### ISSUE TITLE
Getting ads again on Firefox 85.0b2

### ISSUE THREAD

**Issue by d3athrow** [odensc/ttv-ublock#24]
Got this just now. Addon is 2.1.0 with no available updates.
![](http://game.ss13.moe/uploads/2020-12-20_13-45-04.png)

**Comment by gilladur** [comment]
same her, but just on some streams - currently hjune

**Comment by Nixill** [comment]
Confirmed too. It popped up in the middle of watching a stream and then every refresh.

**Comment by sguzikowski** [comment]
Just started happening on my end as well.

**Comment by bottleblue** [comment]
We had a good run on this new extension. No ads up until now.

**Comment by Morten79** [comment]
Dup of https://github.com/odensc/ttv-ublock/issues/21

**Comment by RoyRiv3r** [comment]
bro why can't people read

**Comment by bottleblue** [comment]
Well to be fair the title of that thread is incorrect. Twitch is working fine. It's the extension that's not working properly anymore.

**Comment by d3athrow** [comment]
@Morten79 Issue is misnamed and implies the extension breaks twitch.

**Comment by odensc** [comment]
Merging into #21
