### ISSUE TITLE
how install in edge?

### ISSUE THREAD

**Issue by Warfenix** [odensc/ttv-ublock#6]
hello,

I have seen that these instructions are for chrome and firefox, but I cannot find it for other browsers such as edge.
It works the same for chrome and edge since they are both based on chromium (?)

**Comment by maphex** [comment]
The new edge is based on Chromium just like Google Chrome install process should be the same as Chrome install.

**Comment by odensc** [comment]
I'm not quite sure how to load an unpacked extension on Edge, but it's currently pending review on the Edge addon store.

**Comment by ASoggySandal** [comment]
If you want it ASAP it looks fairly straightforward to load in the unpacked chrome version:
[https://i.imgur.com/HInKfF1.png](https://i.imgur.com/HInKfF1.png)
![Guide image](https://i.imgur.com/HInKfF1.png "Edge guide image")

**Comment by odensc** [comment]
Thanks @ASoggySandal for the great screenshot. I'll close this and will be updating when the extension is approved on Edge.
