### ISSUE TITLE
Constant Errors

### ISSUE THREAD

**Issue by jonyroda97** [odensc/ttv-ublock#7]
I keep getting `Error #2000` and sometimes `Error #1000` when using the extension on Chrome.
I can fix it easily by refreshing page or using the reset player button of the FFZ extension but it's becoming a little annoying to have to do it several times (10 in 10 minutes, sometimes less).

Is there any fix for this?
If not, can the extension auto reset the player when it detects this error?

**Comment by imatimba** [comment]
https://tester798.github.io/ffzenhancing/
This FFZ addon can reset the player automatically on #xxxx errors. You can find the setting in the FFZ Add-On category.

**Comment by jonyroda97** [comment]
Thanks. I will check it out.

Edit:
Good workaround for now.
I will keep this issue open until some DEV answers that nothing can be done about it or there's a fix.

**Comment by odensc** [comment]
I occasionally got these errors even before any adblock script/extension. I think it's just a Twitch bug. I haven't really noticed them get more frequent with the extension though... can you see if there's still an issue with the latest extension that uses a different workaround?

**Comment by odensc** [comment]
Closing for no response, please re-open if you still have this issue with the latest extension, and it doesn't happen without the extension.
