### ISSUE TITLE
Ads rolling again  :(

### ISSUE THREAD

**Issue by Roddi48** [odensc/ttv-ublock#9]
I´m using this Extension for a few Days now. Everything was fine and nice and clean without Ads, i was so happy, and now they are back. I hope you find a new solution. You are all doing a very great Job.  <3

I´m using the Extension with Firefox in Europe, Germany.

greetings

**Comment by maggiojoe2** [comment]
An update will fix: https://github.com/odensc/ttv-ublock/issues/8#issuecomment-728633409

**Comment by wundertuete** [comment]
> An update will fix: [#8 (comment)](https://github.com/odensc/ttv-ublock/issues/8#issuecomment-728633409)

doesn't work for Chrome. Getting midroll ads with Version: 1.1.1

**Comment by serenadezzz** [comment]
I have updated and still having invasive ads.

**Comment by SlyCooperReloadCoded** [comment]
Updated and still getting ads.  If only Twitch would care this much about everything on their site.

**Comment by Bucky420** [comment]
when the streamer rolls ads i get them u have to go to another channel then go back and it prevents the ad from reapearing as a refresh doesent fix it

**Comment by MirTeiwaz** [comment]
Can confirm I am getting ads again (Chrome). Even going to another channel and returning doesn't make the ad disappear.

**Comment by jwd83** [comment]
Also getting ads again

**Comment by jwd83** [comment]
I was having this problem but updating the addon with the new code from github and restarting chrome completely seems to have fixed the problem

**Comment by codydbgt** [comment]
just got anohter one it was a sony avert. 
it is VERY rare for me to get an avert but i think they lock you to wait with a timer no matter a refresh or changing channel it will play but after some time(20-30sec) it will stop poping up. not shure if this is helpfule.
